// AUTO-GENERATED COPY — edit functions/lib/shared.js and run
// `node functions/scripts/sync_shared.js`. Do not edit this file.
/**
 * shared.js — cross-cutting helpers for every Rollaway DO Function.
 *
 * SINGLE SOURCE OF TRUTH lives at functions/lib/shared.js.
 * Copies inside each package dir (functions/packages/rollaway/<fn>/shared.js)
 * are generated by `node functions/scripts/sync_shared.js` — DO Functions
 * bundles each function directory independently, so the file must physically
 * exist in each. NEVER edit the per-function copies by hand.
 *
 * Provides (per docs/CONTRACTS.md §B cross-cutting rules):
 *  - input validation (SF bounds, radius caps)  -> BAD_INPUT
 *  - upstream fetch with timeout + retry/backoff -> UPSTREAM_TIMEOUT / RATE_LIMIT
 *  - the common error envelope { error: { code, message } }
 *  - a per-container TTL cache (best-effort: DO Functions containers are
 *    reused warm between invocations, so this saves quota, but it is NOT a
 *    durable cache — each cold start begins empty)
 */

'use strict';

const fsMod = require('fs');
const pathMod = require('path');

// ---------------------------------------------------------------------------
// Geography constants
// ---------------------------------------------------------------------------

// Loose bounding box around San Francisco proper (covers Treasure Island and
// the Zoo, rejects Oakland/Daly City-and-beyond garbage input).
const SF_BOUNDS = {
  minLat: 37.68,
  maxLat: 37.86,
  minLng: -122.55,
  maxLng: -122.32,
};

const METERS_PER_FOOT = 0.3048;
const FEET_PER_METER = 1 / METERS_PER_FOOT;

const DAYS = ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'];
const DAY_FULL = {
  mon: 'Monday', tue: 'Tuesday', wed: 'Wednesday', thu: 'Thursday',
  fri: 'Friday', sat: 'Saturday', sun: 'Sunday',
};

const VENDOR_TYPES = ['truck', 'trailer', 'pushcart_cooking', 'pushcart_nocook'];

// ---------------------------------------------------------------------------
// Error envelope (CONTRACTS.md §B "Common error envelope")
// ---------------------------------------------------------------------------

const HTTP_STATUS = {
  BAD_INPUT: 400,
  RATE_LIMIT: 429,
  UPSTREAM_TIMEOUT: 504,
};

/** Error carrying one of the contract error codes through the call stack. */
class UpstreamError extends Error {
  constructor(code, message) {
    super(message);
    this.code = code; // 'UPSTREAM_TIMEOUT' | 'RATE_LIMIT' | 'BAD_INPUT'
  }
}

/** Build the DO Function HTTP response for the common error envelope. */
function errorResponse(code, message) {
  return {
    statusCode: HTTP_STATUS[code] || 500,
    headers: { 'Content-Type': 'application/json' },
    body: { error: { code, message } },
  };
}

/** Build a successful DO Function HTTP response. */
function ok(body) {
  return {
    statusCode: 200,
    headers: { 'Content-Type': 'application/json' },
    body,
  };
}

/**
 * Wrap a Function's main() so that no raw stack trace or blank 500 can ever
 * escape: unexpected exceptions become an UPSTREAM_TIMEOUT envelope, and
 * UpstreamError codes are passed through.
 */
function guard(handler) {
  return async function main(args) {
    try {
      return await handler(args || {});
    } catch (err) {
      if (err instanceof UpstreamError) {
        return errorResponse(err.code, err.message);
      }
      console.error('unhandled error:', err && err.stack ? err.stack : err);
      return errorResponse(
        'UPSTREAM_TIMEOUT',
        'Unexpected internal failure while assembling the response.'
      );
    }
  };
}

// ---------------------------------------------------------------------------
// Input validation -> BAD_INPUT
// ---------------------------------------------------------------------------

/**
 * Parse and validate lat/lng/radius_m from raw args (DO web functions deliver
 * query params as strings). Returns { lat, lng, radius_m } or throws
 * UpstreamError('BAD_INPUT').
 */
function validatePoint(args, { defaultRadius = 500, maxRadius = 5000 } = {}) {
  const lat = Number(args.lat);
  const lng = Number(args.lng);
  if (!Number.isFinite(lat) || !Number.isFinite(lng)) {
    throw new UpstreamError('BAD_INPUT', 'lat and lng are required numbers.');
  }
  if (
    lat < SF_BOUNDS.minLat || lat > SF_BOUNDS.maxLat ||
    lng < SF_BOUNDS.minLng || lng > SF_BOUNDS.maxLng
  ) {
    throw new UpstreamError(
      'BAD_INPUT',
      `Point (${lat}, ${lng}) is outside the supported San Francisco area ` +
      `(lat ${SF_BOUNDS.minLat}..${SF_BOUNDS.maxLat}, lng ${SF_BOUNDS.minLng}..${SF_BOUNDS.maxLng}).`
    );
  }
  let radius_m = args.radius_m === undefined ? defaultRadius : Number(args.radius_m);
  if (!Number.isFinite(radius_m) || radius_m <= 0) {
    throw new UpstreamError('BAD_INPUT', 'radius_m must be a positive number.');
  }
  if (radius_m > maxRadius) {
    throw new UpstreamError(
      'BAD_INPUT',
      `radius_m ${radius_m} exceeds the maximum of ${maxRadius} for this function.`
    );
  }
  return { lat, lng, radius_m };
}

/** Validate an optional day-of-week arg ('mon'..'sun'). */
function validateDay(raw, { required = false } = {}) {
  if (raw === undefined || raw === null || raw === '') {
    if (required) throw new UpstreamError('BAD_INPUT', "day is required ('mon'..'sun').");
    return null;
  }
  const day = String(raw).slice(0, 3).toLowerCase();
  if (!DAYS.includes(day)) {
    throw new UpstreamError('BAD_INPUT', `day must be one of ${DAYS.join(', ')} (got '${raw}').`);
  }
  return day;
}

/** Validate an optional 'HH:MM' 24h time arg. Returns minutes-since-midnight or null. */
function validateTime(raw) {
  if (raw === undefined || raw === null || raw === '') return null;
  const m = /^([01]?\d|2[0-3]):([0-5]\d)$/.exec(String(raw).trim());
  if (!m) {
    throw new UpstreamError('BAD_INPUT', `time must be 'HH:MM' 24-hour format (got '${raw}').`);
  }
  return Number(m[1]) * 60 + Number(m[2]);
}

/** Validate an optional 'YYYY-MM-DD' date arg. Returns the string or null. */
function validateDate(raw, name) {
  if (raw === undefined || raw === null || raw === '') return null;
  const s = String(raw).trim();
  if (!/^\d{4}-\d{2}-\d{2}$/.test(s) || Number.isNaN(Date.parse(s))) {
    throw new UpstreamError('BAD_INPUT', `${name} must be 'YYYY-MM-DD' (got '${raw}').`);
  }
  return s;
}

// ---------------------------------------------------------------------------
// Upstream fetch: timeout + retry/backoff -> UPSTREAM_TIMEOUT / RATE_LIMIT
// ---------------------------------------------------------------------------

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * fetch JSON from an upstream with a hard timeout and bounded retry/backoff.
 * - 429 upstream        -> UpstreamError('RATE_LIMIT') (retried once first)
 * - timeout / 5xx / net -> retried `retries` times, then UpstreamError('UPSTREAM_TIMEOUT')
 */
async function fetchJSON(url, {
  timeoutMs = 8000,
  retries = 2,
  backoffMs = 400,
  headers = {},
  method = 'GET',
  body = undefined,
} = {}) {
  let lastErr;
  for (let attempt = 0; attempt <= retries; attempt++) {
    if (attempt > 0) await sleep(backoffMs * Math.pow(2, attempt - 1));
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), timeoutMs);
    try {
      const res = await fetch(url, {
        method,
        headers,
        body,
        signal: controller.signal,
      });
      if (res.status === 429) {
        lastErr = new UpstreamError('RATE_LIMIT', `Upstream rate limit hit for ${hostOf(url)}.`);
        continue; // one more attempt after backoff, then surface RATE_LIMIT
      }
      if (!res.ok) {
        lastErr = new Error(`HTTP ${res.status} from ${hostOf(url)}`);
        if (res.status >= 400 && res.status < 500) break; // 4xx won't heal on retry
        continue;
      }
      return await res.json();
    } catch (err) {
      lastErr = err;
    } finally {
      clearTimeout(timer);
    }
  }
  if (lastErr instanceof UpstreamError) throw lastErr;
  throw new UpstreamError(
    'UPSTREAM_TIMEOUT',
    `Upstream ${hostOf(url)} failed after ${retries + 1} attempts: ${lastErr ? lastErr.message : 'unknown error'}.`
  );
}

function hostOf(url) {
  try { return new URL(url).host; } catch { return url; }
}

/** Standard headers for Socrata (data.sfgov.org): app token lifts rate limits. */
function socrataHeaders() {
  const h = { Accept: 'application/json' };
  if (process.env.SOCRATA_APP_TOKEN) h['X-App-Token'] = process.env.SOCRATA_APP_TOKEN;
  return h;
}

// ---------------------------------------------------------------------------
// TTL cache (per warm container; TTLs documented per call site)
// ---------------------------------------------------------------------------

class TTLCache {
  constructor() { this.map = new Map(); }
  get(key) {
    const hit = this.map.get(key);
    if (!hit) return undefined;
    if (Date.now() > hit.expires) { this.map.delete(key); return undefined; }
    return hit.value;
  }
  set(key, value, ttlMs) {
    this.map.set(key, { value, expires: Date.now() + ttlMs });
  }
  /** get-or-compute helper */
  async getOrSet(key, ttlMs, fn) {
    const hit = this.get(key);
    if (hit !== undefined) return hit;
    const value = await fn();
    this.set(key, value, ttlMs);
    return value;
  }
}

// ---------------------------------------------------------------------------
// Distance (haversine) — used for radius FILTERING of upstream rows only.
// The legal clearance invariant in check_clearance uses turf.js geodesics.
// ---------------------------------------------------------------------------

function haversineMeters(lat1, lng1, lat2, lng2) {
  const R = 6371008.8; // mean earth radius, meters
  const toRad = (d) => (d * Math.PI) / 180;
  const dLat = toRad(lat2 - lat1);
  const dLng = toRad(lng2 - lng1);
  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) * Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(a));
}

// ---------------------------------------------------------------------------
// Demo-reliability spine: DEMO_DATA_MODE + snapshot layer + fail-fast fetch
// (AGENT-BRIEF-functions-data.md §2). Every Function wraps its live data path
// in withData(); on the demo build a snapshot is read, and in live mode a
// transient upstream miss fail-fast-degrades to the frozen snapshot instead of
// surfacing an error. Snapshots store the Function's OUTPUT BODY (the object
// passed to ok()), and contain only public data — never secrets.
// ---------------------------------------------------------------------------

/** Loose truthiness for env flags: '1' | 'true' | 'on' | 'yes' (case-insensitive). */
function truthy(v) {
  if (v === true) return true;
  if (v === undefined || v === null) return false;
  return ['1', 'true', 'on', 'yes'].includes(String(v).trim().toLowerCase());
}

/** DEMO_DATA_MODE on ⇒ read frozen snapshots instead of hitting live APIs. */
function isDemoMode() {
  return truthy(process.env.DEMO_DATA_MODE);
}

// Resolve the demo_data directory once. The synced per-function copy lives at
// <fnDir>/demo_data (created by sync_shared.js); when this module is the
// canonical functions/lib/shared.js (scripts import it directly), __dirname is
// functions/lib, so the sibling functions/demo_data is used instead.
let _demoDir = null;
function demoDataDir() {
  if (_demoDir !== null) return _demoDir;
  const candidates = [
    pathMod.join(__dirname, 'demo_data'),        // per-function synced copy
    pathMod.join(__dirname, '..', 'demo_data'),  // functions/lib -> functions/demo_data
  ];
  for (const dir of candidates) {
    try { if (fsMod.existsSync(dir)) { _demoDir = dir; return _demoDir; } } catch { /* ignore */ }
  }
  _demoDir = candidates[0]; // default (may not exist yet; loadSnapshot handles absence)
  return _demoDir;
}

/**
 * Deterministic snapshot key from the significant args. A single canonical
 * builder so freeze + read can never drift (freeze_snapshots.mjs imports THIS
 * function). Shape: `<lat4>_<lng4>_<radius>_<day>_<time|hour>[_<vendor_type>]`.
 * vendor_type is appended only when present (check_clearance), so keys for the
 * point-only functions are unchanged.
 */
function snapshotKey(args = {}) {
  const a = args || {};
  const lat = Number(a.lat);
  const lng = Number(a.lng);
  const latS = Number.isFinite(lat) ? lat.toFixed(4) : 'na';
  const lngS = Number.isFinite(lng) ? lng.toFixed(4) : 'na';
  const radius = a.radius_m !== undefined && a.radius_m !== null && a.radius_m !== ''
    ? String(a.radius_m) : '';
  const day = a.day ? String(a.day).slice(0, 3).toLowerCase() : '';
  let timePart = '';
  if (a.time !== undefined && a.time !== null && a.time !== '') timePart = String(a.time);
  else if (a.hour !== undefined && a.hour !== null && a.hour !== '') timePart = String(a.hour);
  const base = `${latS}_${lngS}_${radius}_${day}_${timePart}`;
  const vt = a.vendor_type ? String(a.vendor_type).toLowerCase() : '';
  const key = vt ? `${base}_${vt}` : base;
  // Filename-safe: the key becomes part of a filename, and ':' in a time like
  // "12:00" is illegal on Windows (silently creates an NTFS alternate data
  // stream). Strip anything outside [A-Za-z0-9._-] so keys are portable and
  // read/write always agree.
  return key.replace(/[^A-Za-z0-9._-]/g, '');
}

/**
 * Read functions/demo_data/<fnName>.<key>.json and return the parsed OUTPUT
 * BODY, or null when the snapshot is absent/unreadable.
 */
function loadSnapshot(fnName, key) {
  const file = pathMod.join(demoDataDir(), `${fnName}.${key}.json`);
  try {
    if (!fsMod.existsSync(file)) return null;
    return JSON.parse(fsMod.readFileSync(file, 'utf8'));
  } catch (err) {
    console.error(`loadSnapshot(${fnName}, ${key}) failed:`, err.message);
    return null;
  }
}

/**
 * The wrapper every Function uses around its live data-gathering logic.
 *  - DEMO_DATA_MODE on : return the frozen snapshot; if it is MISSING, fall
 *    through to liveFn() (a freeze gap must never 404 the demo) and warn.
 *  - live mode         : run liveFn(); on failure degrade to the snapshot when
 *    one exists (the fail-fast degrade), else rethrow.
 * `liveFn` returns the OUTPUT BODY (what you'd pass to ok()); withData returns
 * a body too, so the caller does `return ok(await withData(...))`.
 */
async function withData(fnName, args, liveFn) {
  const key = snapshotKey(args);
  if (isDemoMode()) {
    const snap = loadSnapshot(fnName, key);
    if (snap !== null) return snap;
    console.warn(`DEMO_DATA_MODE: no snapshot for ${fnName}.${key} — falling through to live`);
    return await liveFn();
  }
  try {
    return await liveFn();
  } catch (err) {
    const snap = loadSnapshot(fnName, key);
    if (snap !== null) {
      console.error('degraded to snapshot:', err && err.message ? err.message : err);
      return snap;
    }
    throw err;
  }
}

/**
 * Fail-fast fetch profile. On the demo build (or when DEMO_FAILFAST is set) a
 * live miss aborts in ~2.5s with no retries and degrades to snapshot, instead
 * of ~20s of retry/backoff. Spread it LAST into fetchJSON opts so it overrides
 * the live defaults only on the demo/fail-fast build; otherwise it is a no-op.
 */
function demoFetchOpts() {
  if (isDemoMode() || truthy(process.env.DEMO_FAILFAST)) {
    return { timeoutMs: 2500, retries: 0 };
  }
  return {};
}

module.exports = {
  SF_BOUNDS,
  METERS_PER_FOOT,
  FEET_PER_METER,
  DAYS,
  DAY_FULL,
  VENDOR_TYPES,
  UpstreamError,
  errorResponse,
  ok,
  guard,
  validatePoint,
  validateDay,
  validateTime,
  validateDate,
  fetchJSON,
  socrataHeaders,
  TTLCache,
  haversineMeters,
  // demo-reliability spine (§2)
  truthy,
  isDemoMode,
  loadSnapshot,
  snapshotKey,
  withData,
  demoFetchOpts,
  demoDataDir,
};
