/**
 * sync_shared.js — copy the single-source shared helper into every function
 * package directory. DigitalOcean Functions bundles each function dir
 * independently, so shared code must physically exist in each; this script
 * keeps functions/lib/shared.js as the only editable copy.
 *
 * Run after any edit to functions/lib/shared.js:
 *   node functions/scripts/sync_shared.js
 */

'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SOURCE = path.join(ROOT, 'lib', 'shared.js');
const PACKAGES_DIR = path.join(ROOT, 'packages', 'rollaway');

const HEADER =
  '// AUTO-GENERATED COPY — edit functions/lib/shared.js and run\n' +
  '// `node functions/scripts/sync_shared.js`. Do not edit this file.\n';

const src = fs.readFileSync(SOURCE, 'utf8');
const fnDirs = fs
  .readdirSync(PACKAGES_DIR, { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => d.name);

for (const dir of fnDirs) {
  const dest = path.join(PACKAGES_DIR, dir, 'shared.js');
  fs.writeFileSync(dest, HEADER + src);
  console.log(`synced -> ${path.relative(ROOT, dest)}`);
}
console.log(`done (${fnDirs.length} function dirs).`);
